spring:
  datasource:
    username: ${MYSQL_DATABASE_USER:root}
    password: ${MYSQL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DATABASE_HOST:localhost}:3306/${MYSQL_DATABASE_NAME:dataset_service_local}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: local
com:
  dataset:
    service:
      base-url: http://localhost:${server.port}
server:
  port: 8080
